version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_DB=test_db'


  app:
    build: ./
    container_name: 'java'
    ports:
      - "8080:8080"
